### ISSUE TITLE
Separation of calibration procedure and main runtime code in deployment

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-python#27]
To run an experiment, we follow these steps:
1. empty arena (no bees), lighting same as experiment (typically dark room)
2. CASUs calibrate IR sensors (to establish a threshold for each sensor)
3. main runtime code starts
4. Bees can be placed in arena

2 & 3 happen like this because they are part of the same program, but actually 3 could happen after 4.

Can we separate the main runtime/user code from the calibration program?
We can run calibration, record the calibration levels to file, then stop program.  Then the main program executes, with levels already known.

Benefits:
- reset of user code while bees are still present (e.g., after correcting a mistake)
- allows calibration code module to be shared more trivially
- calibration levels are explicitly recorded

Downsides:
- every experiment generates 2 logs per CASU.

a) is it possible to run >1 program, in sequence, with fabric? 
b) is it possible to run the two programs independently? (Step 4 above is manual and takes a variable amount of time)
c) could we put the location of the calibration data in the RTC file? (making assumptions generally bad, although it would be borderline acceptable to use "/tmp/IRsensors.calibration" or something, since we definitely don't want these values persisting between resets)

**Comment by dmiklic** [comment]
Since calibration and the "main program" are actually two separate things, and the same calibration routine can (and probably will) be used with lots of different "main programs", for me the most natural solution is to do two consecutive deployments. The calibration routine would create a calibration file which would be used by the "main program". The only remaining problem is retrieving this calibration file (which would then be included in the deployment files of the main program). Implementing an automatic way to do this is something I could probably do by the end of the week.

Let me know if this solution sounds ok to you, and I'll do my best to implement it by Sunday.

**Comment by rmm-fcul** [comment]
Your proposed solution makes sense, and will do the trick nicely.  It seems to cleanly handle developments in calibration, or different calibration procedures for different types of experiment.

Some aspects to consider: 
1. feedback to the experimenter - when has the calibration finished? 
2. can the two deployments take note of different lines in the same .dep file, rather than creating more config files?
3. the calibration program will terminate, whereas many experiments' "main program" will run continuously until user interrupt.

**Comment by dmiklic** [comment]
Hi Rob, have you tried out b5b8037277e5189103db140d0ae65dec8bc370c7 ? If it works, we can close this issue.

**Comment by rmm-fcul** [comment]
I have had a go with this, and there is one catch-22 type issue:

The retrieved (calibration) file goes is in the `data_<project>/<arena>/`

but the filename is identical for all casus. (they don't know their own name, do they?) So when they are retrieved, the last CASU's file overwrites all the others. 

Conversely, if the filename wasn't identical, the `.dep` file would need to have heterogeneous naming, and also somehow to telll the "main program" what the calibration file name is.
Explicit naming strikes me as error-prone, unless it is tied directly to the casu name.
(Having said that, at present I am assuming the calibration file has name that is known to the main controller; see issue #31 that will allow for avoiding this).

**Comment by rmm-fcul** [comment]
There is also the bloat issue, with more .assisi/.dep files.  We need basically the same information, twice over.  This is bad news for maintainability (/experiments going wrong...)

Can we do one of the following (or a better alternative if possible)?

a) have sub-blocks in the `.dep` file, which would manage the different stages.

```yaml
sim-01 :
    casu-001 :
        # shared settings for both/all stages
        hostname : localhost
        user : assisi
        prefix : deploy
        # specific to each stage
        calibration:
            controller: controllers/calibration.py
            extra : []
            output: [calibration_file.test,]
        main: 
            controller: controllers/blink_and_send.py
            output: []
            extra : [controllers/additional_file_1.dummy, calibration_file.test,]
```

or possibly as a lower-effort version (only lower-effort in tool dev, not for user):
b) have the `.assisi` file define both deployment files (calibration and main).

Both options would then need the deploy/assisirun/collect_data scripts to accept a flag for whether they were operating on the calibration or main stage.  (Note that argparse allows option groups, and these can come from a shared library so all the tools could use common parse/options code).
